apiVersion: v1
kind: ServiceAccount
metadata:
  name: restricted-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-demo
  template:
    metadata:
      labels:
        app: rbac-demo
    spec:
      serviceAccountName: restricted-user
      containers:
        - name: app
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - kubectl get secrets -A; sleep 3600
