apiVersion: v1
kind: Pod
metadata:
  name: basic-pod
spec:
  containers:
    - name: basic-container
      image: busybox:1.36
      command: ["/bin/sh", "-c"]
      args:
        - echo "Application starting";
